services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ai-platform-postgres
    environment:
      POSTGRES_DB: ai_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./packages/backend/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ai-platform-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: ai-platform-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai-platform-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    container_name: ai-platform-backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ai_platform
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-jwt-secret-key
      JWT_REFRESH_SECRET: your-jwt-refresh-secret-key
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./packages/backend:/app
      - /app/node_modules
    networks:
      - ai-platform-network
    command: npm run dev

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    container_name: ai-platform-frontend
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - ai-platform-network
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  ai-platform-network:
    driver: bridge